insomniacslk/dhcp

.stickler.yml

Using Stickler-ci.com for golint bot

Added stickler config for golint bot

---

dhcpv6/client.go

Implemented `NewClient` and addressed linter warnings

dhcpv6: implemented NewClient and addressed linter warnings

---

dhcpv4/bsdp/bsdp.go
dhcpv4/dhcpv4.go
dhcpv4/option_class_identifier.go
dhcpv4/option_class_identifier_test.go
dhcpv4/option_generic.go
dhcpv4/option_generic_test.go
dhcpv4/option_maximum_dhcp_message_size.go
dhcpv4/option_maximum_dhcp_message_size_test.go
dhcpv4/option_message_type.go
dhcpv4/option_message_type_test.go
dhcpv4/option_parameter_request_list.go
dhcpv4/option_parameter_request_list_test.go
dhcpv4/option_requested_ip_address.go
dhcpv4/option_requested_ip_address_test.go
dhcpv4/option_server_identifier.go
dhcpv4/option_server_identifier_test.go
dhcpv4/options.go
dhcpv4/options_test.go
dhcpv4/types.go

This PR adds some more specific options to dhcpv4. Currently, only the ones used by the main dhcpv4 package will be added.

Add more specific dhcpv4 options

---

dhcpv4/bsdp/bsdp.go
dhcpv4/bsdp/bsdp_option_boot_image_list.go
dhcpv4/bsdp/bsdp_option_boot_image_list_test.go
dhcpv4/bsdp/bsdp_option_default_boot_image_id.go
dhcpv4/bsdp/bsdp_option_default_boot_image_id_test.go
dhcpv4/bsdp/bsdp_option_generic.go
dhcpv4/bsdp/bsdp_option_generic_test.go
dhcpv4/bsdp/bsdp_option_machine_name.go
dhcpv4/bsdp/bsdp_option_machine_name_test.go
dhcpv4/bsdp/bsdp_option_server_identifier.go
dhcpv4/bsdp/bsdp_option_server_identifier_test.go
dhcpv4/bsdp/bsdp_option_server_priority.go
dhcpv4/bsdp/bsdp_option_server_priority_test.go
dhcpv4/bsdp/bsdp_test.go
dhcpv4/bsdp/client.go
dhcpv4/bsdp/option_vendor_specific_information.go
dhcpv4/bsdp/option_vendor_specific_information_test.go
dhcpv4/bsdp/types.go
dhcpv4/dhcpv4.go

Added more BSDP specific options + an implementation of the vendor specific options.

Add some more specific bsdp options + vendor specific implementation

---

dhcpv6/option_archtype.go
dhcpv6/option_archtype_test.go

More testing love for DHCPv6 options

Added tests for OptClientArchType

---

dhcpv6/option_serverid.go
dhcpv6/option_serverid_test.go

Added tests for OptServerId

---

dhcpv6/option_dnsrecursivenameserver.go
dhcpv6/option_dnsrecursivenameserver_test.go
netboot/netconf.go

* Made public the NameServers field like in the other options.
* Removed setter and getter
* Added tests

OptDNSRecursiveNameServer gets public fields and tests, removes setter and getter

---

dhcpv6/option_bootfileurl.go
dhcpv6/option_bootfileurl_test.go
netboot/netboot.go

For consistency with the rest of the library

OptBootFileURL fields are now public

---

dhcpv4/option_domain_name_server.go
dhcpv4/option_domain_name_server_test.go
dhcpv4/options.go

Added option decoder for the Domain Name Server option in DHCPv4
(tests coming in the next commit)

Added OptDomainNameServer for DHCPv4

---

dhcpv6/client.go

The logic that applies the modifiers was just wrong in Exchange():
1. it was not applied to SOLICIT packets
2. it was applied on the REQUEST *after* it was sent (wth did I have in mind?)
This patch fixes the modifiers misbehaviour

DHCPv6.Exchange now applies modifiers correctly for both solicit and request

---

dhcpv6/option_nontemporaryaddress.go
dhcpv6/option_nontemporaryaddress_test.go

Added OptIANA.GetOneOption to fetch a given option within an OptIANA.Options

Optiana GetOneOption

---

dhcpv4/option_userclass.go
dhcpv4/option_userclass_test.go

Added support for UserClass options for DHCPv4 as per the [RFC](https://tools.ietf.org/html/rfc3004)

Added UserClass option to DHCPv4

---

dhcpv4/option_bootfile_name.go
dhcpv4/option_bootfile_name_test.go

[RFC](https://tools.ietf.org/html/rfc2132)

Add support for Bootfile name option

---

dhcpv4/option_tftp_server_name.go
dhcpv4/option_tftp_server_name_test.go
dhcpv4/options.go

[RFC](https://tools.ietf.org/html/rfc2132)

Add TFTP server name option

---

dhcpv4/bsdp/bsdp.go
dhcpv4/dhcpv4.go
dhcpv4/dhcpv4_test.go

add NewReplyFromRequest which builds a DHCPv4 reply from a request.
Also add more logic to the AddOption to insert options before the OptionEnd.

add NewReplyFromRequest

---

dhcpv4/option_userclass.go
dhcpv4/option_userclass_test.go

https://github.com/insomniacslk/dhcp/issues/113

Parse non-RFC compliant user class

---

dhcpv4/client.go
dhcpv4/dhcpv4.go
dhcpv4/dhcpv4_test.go
dhcpv4/option_bootfile_name.go
dhcpv4/option_bootfile_name_test.go
dhcpv4/option_tftp_server_name.go
dhcpv4/option_tftp_server_name_test.go

This is to make it more consistent with other functions.
Also update the OptTFTPServerName and OptBootfileName String function also for consistency with other options.

rename RequestFromOffer to NewRequestFromOffer

---

dhcpv4/option_archtype.go
dhcpv4/option_archtype_test.go
dhcpv6/dhcpv6.go
dhcpv6/dhcpv6_test.go
dhcpv6/modifiers.go
dhcpv6/option_archtype.go
dhcpv6/option_archtype_test.go
iana/archtype.go

* support multiple arch types (fixes #120)
* move arch types to iana package

fix OptClientArchType

---

.travis.yml

This is the base to start supporting Go versioned modules

Travis go111

---

dhcpv4/async/client.go
dhcpv4/async/client_test.go

A prototype of DHCPv4 Async client. Fixes #89.

Async DHCPv4 client

---

dhcpv6/modifiers.go
dhcpv6/modifiers_test.go
dhcpv6/option_requestedoption.go

Modifier for adding requested options easily

ORO Modifier

---

dhcpv4/option_vivc.go
dhcpv4/option_vivc_test.go

We currently don't have clients sending this option that is why we didn't detect it before.

fix ParseOptVIVC

---

dhcpv6/option_vendorclass.go
dhcpv6/option_vendorclass_test.go
dhcpv6/options.go

* add vendor class option
* reorder the parsing of options

add OptVendorClass

---

dhcpv4/modifiers.go
dhcpv4/modifiers_test.go

Modifier which sets the parameters of DHCPv4 packet to relay.

DHCPv4 relay modifier

---

dhcpv6/client.go

Fixes https://github.com/insomniacslk/dhcp/issues/159

Added listener timeout to the dhcpv6 client

---

dhcpv4/option_root_path.go
dhcpv4/option_root_path_test.go
dhcpv4/options.go
dhcpv4/options_test.go

Adds a root path option that supports DHCPv4 option 17

dhcpv4: Add OptRootPath

---

dhcpv6/option_archtype_test.go
dhcpv6/option_bootfileurl_test.go
dhcpv6/option_clientid_test.go
dhcpv6/option_dnsrecursivenameserver_test.go
dhcpv6/option_domainsearchlist_test.go
dhcpv6/option_elapsedtime_test.go
dhcpv6/option_iaaddress_test.go
dhcpv6/option_iaprefix_test.go
dhcpv6/option_interfaceid_test.go
dhcpv6/option_nii_test.go
dhcpv6/option_nontemporaryaddress_test.go
dhcpv6/option_prefixdelegation_test.go
dhcpv6/option_relaymsg_test.go
dhcpv6/option_remoteid_test.go
dhcpv6/option_requestedoption_test.go
dhcpv6/option_serverid_test.go
dhcpv6/option_statuscode_test.go
dhcpv6/option_userclass_test.go
dhcpv6/option_vendorclass_test.go

Resolves the DHCPv6 part of #49

Add some more DHCPv6 option tests.

---

dhcpv4/client.go

When previously implementing the changes to the dhcpv4 client I allowed the user to set a custom `LocalAddr` - but unfortunately I did not adapt `MakeListeningSocket()` to use that value, so if we set a custom port and the server send us packet back to that port we will not see them because we're constantly listening to port 68.
This PR fixes that issue.
Note I did not change the `MakeListeningSocket()` signature since it's public and we'll break backward compatibility. There are good reasons to make `makeListeningSocketWithCustomPort()` public too, so I'm not against doing that if we want to.

Make listening port for dhcpv4 client configurable

---

README.md

Added another project that depends on this library.

Updated README.md to include fbender

---

.travis/tests.sh
dhcpv4/client.go
dhcpv4/dhcpv4.go
dhcpv4/modifiers.go
dhcpv4/modifiers_test.go
dhcpv4/server.go
dhcpv4/server_test.go

Added DHCPv4 server code and tests.
Still WIP. Tests will fail: requires root access; and port 0 and raw sockets.

[WIP] Added DHCPv4 server

---

README.md

Showing how to use DHCPv6 client. First step for #188

Added DHCPv6 client example

---

README.md

Added DHCPv6 packet crafting example

---

dhcpv4/server.go
dhcpv6/server.go

Code for v6 and v4 servers is now consolidated. There are also various bug fixes.

Consolidated v6 and v4 server handlers

---

netboot/netconf.go

netboot: delay in IfUp to avoid hammering the CPU

---

README.md
dhcpv4/server_test.go
dhcpv6/server_test.go
interfaces/interfaces.go
interfaces/interfaces_test.go

There are several places that may benefit from a package with interface facilities, see  https://github.com/systemboot/systemboot/pull/73 for context

interfaces: added package with interface facilities

---

README.md

Signed-off-by: Nikolas Sepos <nikolas.sepos@gmail.com>

Add Go code highlighting in examples

---

dhcpv6/duid.go
dhcpv6/duid_test.go

Added shorthand to compare DUID equality

dhcpv6: added Duid.Equal

---

dhcpv4/async/client.go
dhcpv4/bsdp/bsdp.go
dhcpv4/bsdp/bsdp_test.go
dhcpv4/client.go
dhcpv4/dhcpv4.go
dhcpv4/modifiers.go
dhcpv4/modifiers_test.go
netboot/netconf_test.go

Also drop unnecessary return value of Modifier.

dhcpv4: build all packets with modifiers

---

dhcpv4/dhcpv4.go
dhcpv4/option_routes.go
dhcpv4/option_routes_test.go
dhcpv4/options.go
dhcpv4/types.go

milestone for https://github.com/u-root/u-root/issues/1161

dhcpv4: add RFC3442 route options

---

dhcpv4/nclient4/client.go

Signed-off-by: Christopher Koch <chrisko@google.com>

nclient4: simplify New interface

---

dhcpv4/nclient4/client.go
dhcpv4/nclient4/client_test.go
dhcpv4/server4/server_test.go

Why did I ever think this would work??
Signed-off-by: Christopher Koch <chrisko@google.com>

nclient4: fix conn race condition

---

dhcpv6/async/client_test.go
dhcpv6/dhcpv6_test.go
dhcpv6/dhcpv6message.go
dhcpv6/dhcpv6relay_test.go
dhcpv6/modifiers.go

This reverts commit b071bdc86a58037f6c745647c97fca202f3caef9.
I pushed by mistake. Reverting, and confirmed branch protection on master enabled.

Revert "[dhcpv6] Solicit messages derive default IAID from MAC address"

---

dhcpv6/dhcpv6_test.go
dhcpv6/dhcpv6relay_test.go
dhcpv6/iputils_test.go
dhcpv6/modifiers.go
dhcpv6/nclient6/client.go
dhcpv6/nclient6/client_test.go
dhcpv6/option_iaprefix_test.go
dhcpv6/ztpv6/parse_remote_id_test.go
dhcpv6/ztpv6/parse_vendor_options_test.go

Mostly for dead code and potentially wrong comparisons.

Addressed various linter warnings

---

.travis.yml
.travis/linters.sh
dhcpv4/async/client.go
dhcpv4/async/client_test.go
dhcpv4/bsdp/bsdp.go
dhcpv4/bsdp/bsdp_option_misc_test.go
dhcpv4/bsdp/option_vendor_specific_information.go
dhcpv4/dhcpv4.go
dhcpv4/dhcpv4_test.go
dhcpv4/nclient4/client_test.go
dhcpv4/option_ip_address_lease_time.go
dhcpv4/options.go
dhcpv4/server4/server_test.go
dhcpv4/ztpv4/parse_circuitid_test.go

Now the CI will also run golangci-lint
Fixes https://github.com/insomniacslk/dhcp/issues/104

[CI] Added linters

---

dhcpv4/nclient4/conn_linux.go

When reading raw packets from the network, it can happen that the raw
ethernet packet read has undefined bytes after the end of the ip
packet (either from the network or in some cases from the local
stack).
Those bytes should not be passed to the dhcp-receiver otherwise the
option parser which is picky about final padding byte will silently
discard the dhcp-reply.
Tested: ast2500 bmc reproducing the issue + existing go test for coverage.
Signed-off-by: Loic Prylli <lprylli@netflix.com>

Ignore bytes after end of IP packet in BroadcastRawUDPConn.ReadFrom

---

dhcpv4/nclient4/client.go

nclient4: add logging options

---

dhcpv4/dhcpv4.go

Nobody gives a hoot about the hardware type.

dhcpv4: make the short stringer more useful

---

.travis/tests.sh
netboot/netconf_integ_test.go

Fix TravisCI build

---

dhcpv4/dhcpv4.go

dhcpv4: actually use random number timeout

---

dhcpv4/nclient4/ipv4.go
dhcpv4/ztpv4/parse_circuitid.go

Fixed typos in dhcpv4

---

dhcpv4/nclient4/conn_linux.go
dhcpv4/options.go

No need to convert these types.

Fixed unnecessary conversions

---

dhcpv6/dhcpv6relay.go
dhcpv6/option_elapsedtime.go
dhcpv6/option_remoteid.go
dhcpv6/option_vendor_opts.go
dhcpv6/option_vendorclass.go

Fixed unnecessary conversions in dhcpv6

---

dhcpv4/nclient4/client.go
dhcpv6/nclient6/client.go

nclient6: copy & paste log infra to v6

---

dhcpv4/server4/conn.go
dhcpv6/server6/conn.go

The concrete type under the interface is known here since we create the connection in the same function. Since *net.UDPConn implements net.PacketConn anyway, returning the concrete type here is more powerful and less risky than having downstream users cast the value themselves
There should be no code change for downstream users as the concrete type implements the interface, with the exception of explicit casts (`udpc := conn.(*net.UDPConn)`), which can simply be removed
(I could not find any users of these functions outside the library on github anyway so this looks safe)

server{4,6}: Return UDPConn from NewIPv*UDPConn

---

dhcpv6/option_iaaddress.go
dhcpv6/option_iaaddress_test.go
dhcpv6/option_iaprefix.go
dhcpv6/option_iaprefix_test.go
dhcpv6/option_nontemporaryaddress.go
dhcpv6/option_nontemporaryaddress_test.go
dhcpv6/option_prefixdelegation.go
dhcpv6/option_prefixdelegation_test.go
netboot/netconf.go
netboot/netconf_test.go

v6: use time.Duration for duration fields

---

dhcpv4/server4/server.go

Fixes, among other things, u-root pxeserver

Fix a compare in Serve() of IP4 Zero to use an IP4 address

---

dhcpv6/nclient6/client.go

Supersedes #317. cc @rminnich.

nclient6: allow non-rapid responses to RapidSolicit

---

dhcpv6/modifiers.go
dhcpv6/modifiers_test.go
dhcpv6/option_fqdn.go
dhcpv6/option_fqdn_test.go

dhcpv6 fqdn: fix domain encoding

---

.travis/tests.sh

rtr7 has moved to go modules

---

CONTRIBUTORS.md
README.md

* Add Talos to README
* Add Natolumin to CONTRIBUTORS

update README and CONTRIBUTORS

---

dhcpv6/nclient6/client.go

We're chasing a Heisenbug. 
cc @ganshun (this was Ian's idea)

nclient6: optional dropped packet logging

---

dhcpv6/dhcpv6message.go
dhcpv6/modifiers.go
dhcpv6/option_informationrefreshtime.go
dhcpv6/option_informationrefreshtime_test.go
dhcpv6/options.go

Added structure, parsing and convenience fuctions for OptInformationRefreshTime (32) https://tools.ietf.org/html/rfc8415

Option: Information Refresh Time https://tools.ietf.org/html/rfc8415

---

go.mod
go.sum
netboot/netconf.go

Ref: https://github.com/jsimonetti/rtnetlink/pull/86

netboot: use latest rtnl api

---

dhcpv4/nclient4/client.go

Ensure server identifier matches the offer server identifier when
looking for ACKs or NAKs.
This protects against rogue DHCP servers NAKing requests the shouldn't.
Signed-off-by: Moritz Fischer <moritzf@google.com>

nclient4: Ensure server identifier matches

---

dhcpv4/nclient4/client.go

Fix nclient4 build

---

dhcpv4/dhcpv4.go

[dhcpv4] remove NewOffer comment

---

interfaces/bindtodevice_bsd.go

Follow up from https://github.com/insomniacslk/dhcp/pull/423#issuecomment-895931321
In https://github.com/insomniacslk/dhcp/pull/423 I broke BSD build.

[interfaces] bsd

---

interfaces/bindtodevice_bsd.go

Follow up from https://github.com/insomniacslk/dhcp/pull/438#issuecomment-897282173
In #423 I broke BSD build.

[interfaces] bsd #2

---

dhcpv6/dhcpv6message.go
dhcpv6/option_ntp_server.go
dhcpv6/option_ntp_server_test.go
dhcpv6/options.go

Added OptNTPServer

---

netboot/netconf.go

Signed-off-by: Deomid "rojer" Ryabkov <rojer9@fb.com>

Add NTPServers to NetConf

---

dhcpv6/dhcpv6message.go
dhcpv6/option_ntp_server_test.go

Fix a bug in MessageOptions.NTPServers

---

dhcpv4/nclient4/conn_unix.go

nclient4: support BSDs

---

dhcpv4/ztpv4/parse_circuitid.go
dhcpv4/ztpv4/parse_circuitid_test.go

Signed-off-by: Emanuele Fia <name29@fb.com>

Adding support for more circuit id format

---

.github/workflows/tests.yml
README.md

GH workflows: Go support up to 1.20 and fix badge

---

dhcpv4/ztpv4/ztp.go
dhcpv4/ztpv4/ztp_test.go

Adding support for new juniper format

Adding support for new juniper format

---

dhcpv4/ztpv4/parse_circuitid.go
dhcpv4/ztpv4/parse_circuitid_test.go

I deleted the prevuous two commits I did and pushed a brand new commit that fixed the sign-off and unittests as per @pmazzini comment

Adding arista port-channel support

---

README.md

Update README.md adding Tinkerbell as user of this library

---

dhcpv4/option_relay_agent_information.go
dhcpv4/option_relay_agent_information_test.go
dhcpv4/options.go

Adding decoders for more DHCP options so that DHCP packets are easier to inspect by humans.

Humanize some more options
