insomniacslk/dhcp

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/dhcpv4_test.go, dhcpv4/options_test.go, dhcpv6/dhcpv6_test.go
Refactors all tests to use [stretchr/testify/require](https://godoc.org/github.com/stretchr/testify/require), a nice package with a lot of helper methods for asserting various things in tests + nice formatting for failures.
Plus some fixes for bsdp that didn't make it in the last commit.
Tests:
```
$ go test github.com/insomniacslk/dhcp/dhcpv4
ok  	github.com/insomniacslk/dhcp/dhcpv4	0.146s
$ go test github.com/insomniacslk/dhcp/dhcpv4/bsdp
ok  	github.com/insomniacslk/dhcp/dhcpv4/bsdp	0.106s
$ go test github.com/insomniacslk/dhcp/dhcpv6
ok  	github.com/insomniacslk/dhcp/dhcpv6	0.075s
```
=> Refactor tests to use stretchr/testify/require

dhcpv6/option_relaymsg_test.go
I was using `Fatal` instead of `Fatalf` with format strings. Fixed here
=> Fix use of Fatalf

dhcpv4/bsdp/client.go, dhcpv4/client.go
Previously there was a lot of shared code in the implementations of `dhcpv4.Exchange` and `bsdp.Exchange`. This PR refactors that into a lot of shared code, with only the actual `Exchange` funcs being different (as they should be).
It also compresses the logic of sending out on the broadcast address and receiving from it into a single function.
Testing on an instance where BSDP works properly:
```
DHCPv4
opcode=BootRequest
hwtype=Ethernet
hwaddrlen=6
hopcount=0
transactionid=0xeeb85048
numseconds=0
flags=Unicast (0x00)
clientipaddr=192.168.0.30
youripaddr=0.0.0.0
serveripaddr=0.0.0.0
gatewayipaddr=0.0.0.0
clienthwaddr=<MAC>
serverhostname=
bootfilename=
options=
DHCP Message Type -> [8]
Vendor Specific Information -> [1 1 1 2 2 1 1]
Parameter Request List -> [43 60]
Maximum DHCP Message …
```
=> Refactor client code, add timeout capabilities

dhcpv4/client.go
The previous commit introduced a regression in the DHCPv4 client, due to the way `net.IP` works. The erroneous code was:
```
BroadcastAddressBytes = [4]byte{
net.IPv4bcast[0],
net.IPv4bcast[1],
net.IPv4bcast[2],
net.IPv4bcast[3],
}
```
The first four bytes are all zeros, because `net.IP` can be stored as a 16-bytes slice even for IPv4 addresses. The safest way is to always use `.To4()` to make sure to use the right bytes.
=> dhcpv4: fix client regression

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/option_generic.go, dhcpv4/option_generic_test.go, dhcpv4/options.go, dhcpv4/options_test.go, dhcpv4/types.go
This PR sets the stage for breaking out the implementation of all DHCPv4 options to their own separate options that implement the `dhcpv4.Option` interface. This makes things much more flexible for e.g. BSDP (+ pretty-printing vendor-specific options). This PR also adds an `OptionGeneric`, similar to `dhcpv6.OptionGeneric` that can implement all other options.
Some other small changes:
* Changes `DHCPv4.clientHwAddr` to a `net.HardwareAddr`
* Changes `DHCPv4.serverHostName` to a `string`
* Changes `DHCPv4.bootFileName` to a `string`
=> Make dhcpv4.Option an interface, add OptionGeneric

dhcpv4/option_vivc.go, dhcpv4/option_vivc_test.go, dhcpv4/options.go
Add support for parsing option 124 which is Vendor-Identifying Vendor
Class which is defined in https://tools.ietf.org/html/rfc3925.
=> Add parsing for Option 124: Vendor-Identifying Vendor Class

dhcpv6/client.go, dhcpv6/types.go
Before this patch the client just took whatever DHCP message it
received, without checking if it's what it wants. Now it checks for the
message type.
If the message is not a relay, also check the transaction ID
=> DHCPv6 client now waits for specific packet types

dhcpv6/client.go, dhcpv6/dhcpv6.go, dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go
Added support for packet modifiers, i.e. functions that can arbitrarily
manipulate a DHCPv6 packet. These modifiers are used by NewMessage,
NewSolicitForInterface, NewRequestForAdvertise, and can be used by other
packet creation functions.
A bunch of sample modifiers have been added under modifiers.go , too.
With the introduction of modifiers I also removed some options that
should not necessarily be in a standard DHCPv6 message.
In order to implement modifiers in a consistent manner, this patch also
modifies the return value of the `New*` functions, from `DHCPv6Message`
to `DHCPv6`.
=> dhcpv6: added modifiers

dhcpv6/modifiers.go, dhcpv6/option_userclass.go
Currently OptUserClass only allows for one user class. This patch adds the ability to specify multiple user classes
=> dhcpv6: option userclass: supporting multiple user classes

netboot/netboot.go, netboot/netconf.go
This package adds netboot capabilities for DHCPv6 and DHCPv4.
Currently only DHCPv6 is implemented, but I am going to add v4 support soon.
=> Added netboot package

dhcpv6/duid.go, dhcpv6/option_clientid.go, dhcpv6/option_clientid_test.go
Two things are changed in this diff:
* a breaking change: Duid.LinkLayerAddr is not a `[]byte` anymore but a more appropriate `net.HardwareAddr` (defined as a `[]byte`)
* tests for OptClientId
=> Added tests for OptClientId and using net.HardwareAddr for DUID

dhcpv6/option_statuscode.go, dhcpv6/option_statuscode_test.go, iana/statuscodes.go
Three changes:
* status code and status message are now public - no more accessors, like in the other options
* defined status codes in the `iana` package as per rfc3315
* added unit tests
=> OptStatusCode: public fields, proper codes, and tests

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go
GetOption and GetSingleOption are convience methods for getting a DHCPv4
option from it's Option Code.
GetOption returns a list of options that match since the DHCP RFC allows
for an option to be present multiple times with it's values appened
together.  (Note: I am not sure i've ever seen this done and it's not clear if
how option parsing would work for more complex values.  Is appeneding
done at the byte level? )
GetSingleOption will return the first found option that maches a code
and a bool if it was found or not.
=> add dhcpv4.GetOption and dhcpv4.GetSingleOption methods

netboot/netconf.go
In https://github.com/insomniacslk/dhcp/commit/bdb0bf25259985b962e230fbac5265a7623afd05 I broke the build of the netboot subackage because I mistakenly pushed to master instead of a branch + PR. Since then I've enabled branch protection, and this commit unbreaks the build.
=> Unbreak build after changing OptIANA interface

dhcpv6/duid.go, dhcpv6/duid_test.go
I’m building on a program which works with user-supplied DUIDs. Before this
change, the code would panic when users provide a DUID which is not (yet)
implemented.
In addition to this being a better failure mode, the behavior is also mandated
by the DHCPv6 RFC: https://tools.ietf.org/html/rfc3315#section-9 states:
Clients and servers MUST treat DUIDs as opaque values and MUST only
compare DUIDs for equality.
=> Pass through unknown DUIDs

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
Add a more generic NewReplyFromDHCPv6Message to avoid code duplication.
This is one step closer towards fixing issue #73.
=> add NewReplyFromDHCPv6Message

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
NewSolicit provides functionality between `NewMessage` and `NewSolicitForInterface`, allowing users to create a `SOLICIT` message without the need to provide an interface. This is crucial for generating fake DHCPv6 messages (ex. for a MAC address not associated with a card on the actual device).
=> NewSolicitWithCID for DHCPv6

dhcpv6/future.go
When a future is not being listened to (ex. it timeouts before `AsyncClient` writes a response) a client will be stuck waiting. Making this channel buffered (for one message) fixes the issue.
=> Make Future buffered to avoid concurrency issues

netboot/netboot.go
Currently a netboot attempt will fail if no netboot  URL is returned by the DHCPv6 server.
This patch doesn't make it fail anymore - just the returned URL will be an empty string
=> Netboot: don't fail if no netboot url is returned

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/bsdp/option_vendor_specific_information.go, dhcpv4/bsdp/option_vendor_specific_information_test.go
Refactors BSDP code to use `dhcpv4.GetOneOption` instead of manually
searching through the list of options.
=> BSDP: Refactor to use dhcpv4.GetOneOption

dhcpv4/bsdp/client.go, dhcpv4/client.go, dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/types.go
With this patch, BroadcastSendReceive gains an additional argument that specifies which type of reply it should wait for.
Without this patch, the DHCPv4 client would simply get whatever DHCPv4 reply it got, which doesn't deal well with duplicate packets from multiple DHCP servers.
Additionally, the code that sends the Request in a DORA transaction was wrong, as it was sending the discover again, instead of the request. This is fixed too.
=> [DHCPv4] BroadcastSendReceive now can wait for specific reply types

dhcpv6/client.go, dhcpv6/dhcpv6.go, dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go, dhcpv6/dhcpv6relay.go, dhcpv6/dhcpv6relay_test.go, dhcpv6/option_relaymsg_test.go, dhcpv6/types.go, dhcpv6/utils_test.go, netboot/netboot.go
Renames DHCPv6 constants for message types to CamelCase
=> DHCPv6: Fix message type constants

dhcpv4/dhcpv4_test.go, dhcpv4/modifiers_test.go, dhcpv4/option_userclass.go, dhcpv4/option_userclass_test.go
The ToBytes was always writing a packet in a rfc3004 compliant way while the FromBytes was parsing a user class option either following the rfc3004 or the Microsoft standard.
This will make it more consistent with what we read and write.
=> fix OptUserClass

dhcpv4/bsdp/client.go
As done in https://github.com/insomniacslk/dhcp/pull/121 , return a list of pointers rather than a list of objects to avoid unnecessary copies
=> BSDP: Exchange returns list of pointers, not list of objects

netboot/netboot.go
Before this patch, the WithNetboot modifier was applied twice
=> Fixing duplicate WithNetboot modifier in netboot package

dhcpv4/options.go, dhcpv4/options_test.go
According to the RFC:
>   The end option marks the end of valid information in the vendor
>   field.  Subsequent octets should be filled with pad options.
There are clients sending invalid options after the End Option which breaks the whole packet parsing.
I am not a great fan of this PR though because it may create a mismatch in the length of what we receive and send.
Related issue #131
=> stop parsing after end

dhcpv6/dhcpv6relay.go, dhcpv6/dhcpv6relay_test.go
Add the remote id option when creating a relay reply.
According to https://tools.ietf.org/html/rfc4649#section-5 this shouldn't be needed:
> There is no requirement that a server return this option and its data
> in a RELAY-REPLY message.
However, there are some relay agents that expect this data so I am adding it to the reply.
cc @gorhamc
=> NewRelayReplFromRelayForw: add remoteid

dhcpv4/bsdp/bsdp_option_message_type.go, dhcpv4/bsdp/bsdp_option_message_type_test.go, dhcpv4/bsdp/types.go, dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/option_generic.go, dhcpv4/option_message_type.go, dhcpv4/option_message_type_test.go, dhcpv4/option_parameter_request_list.go, dhcpv4/types.go, dhcpv6/types.go
I've added a String method to all the option/message types so we don't need to check the map manually every time, or to use a function (a method is more intuitive).
Only one exception: bsdp.OptionCode cannot be easily converted to this approach unless we define it as its own type
=> Added String methods for types

dhcpv6/async/client.go, dhcpv6/client.go, dhcpv6/iputils.go, dhcpv6/iputils_test.go
A complementary function for `GetLinkLocalAddr`, but allows to get a global address for the interface. Helpful to setup a client as a relay forwarder.
=> GetGlobalAddr utility function

.travis.yml, .travis/tests.sh
In a couple of commits we broke a project that depends on this library (router7). I've added a simple build of router7 at the end of the tests until we move to a stable API and versioned modules
=> [WIP] Test that we do not break router7 builds

.travis/tests.sh
Removed the workaround from TravisCI tests where we patched manually pcapgo (see https://github.com/insomniacslk/dhcp/pull/152 ), since the relevant gopacket PR has been merged.
=> Removed workaround for pcapgo.OpenEthernet from tests

iana/statuscodes.go
As per https://www.ietf.org/rfc/rfc3633.txt section 16, status code 6 has been reserved for "Delegating router has no prefixes available to assign to the IAPD(s)"
=> Add NoPrefixAvail status code

.travis/tests.sh, dhcpv6/client.go, dhcpv6/client_test.go, dhcpv6/server.go, dhcpv6/server_test.go
Implemented a bare-bone DHCPv6 server code. Now the user can simply provide a handler function
and an address to listen on, to run a basic DHCPv6 server with custom logic.
This also enables integration tests (see `server_test.go` for an example)
Sample run:
Server:
```
$ go run main.go 
2018/09/26 23:57:21 Server listening on [::1]:12345
2018/09/26 23:57:21 Ready to handle requests
2018/09/26 23:57:21 Waiting..
2018/09/27 00:11:37 Handling request from [::1]:42598
2018/09/27 00:11:37 DHCPv6Message
messageType=SOLICIT
transactionid=0xaabbcc
options=[  ]
2018/09/27 00:11:37 Waiting..
^Csignal: interrupt
```
Client:
```
$ echo -en "\x01\xaa\xbb\xcc" | nc -u -6 '::1' 12345 
^C
```
=> Implemented basic DHCPv6 server handler

dhcpv4/bsdp/bsdp_option_boot_image_list.go, dhcpv4/bsdp/bsdp_option_boot_image_list_test.go, dhcpv4/bsdp/option_vendor_specific_information_test.go
While parsing boot images, the current code reads to the end of the data
stream; however, this could lead to reading past the boot image option
and reading into the next option. Instead, contain how far the option
parsing code reads by only looking at the max length specified in the
option.
Before fix, failing tests (added in this PR):
```
$ go test ./...
?       github.com/insomniacslk/dhcp    [no test files]
netboot/netconf.go:118:13: undefined: netlink.AddrReplace
ok      github.com/insomniacslk/dhcp/dhcpv4     (cached)
ok      github.com/insomniacslk/dhcp/dhcpv4/async       (cached)
--- FAIL: TestParseOptBootImageList (0.00s)
bsdp_option_boot_image_list_test.go:129:
Error Trace:    bsdp_option_boot_image_list_test.go:129
Error:          Received unexpected error:
parsing bytes stream: …
```
=> BSDP: Fix parsing offset for boot image lists

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go
This is a helper function to extract the BSDP message type from a given
`dhcpv4.DHCPv4` packet structure. It's useful in helping to identify
what kind of BSDP packet you're dealing with (since the distinction is
only made in one of the vendor-specific options encapsulated in Option
43).
=> BSDP: Add MessageTypeFromPacket helper

dhcpv6/option_prefixdelegation.go, dhcpv6/option_prefixdelegation_test.go
Thoughts on this? I tried to make it look the same as OptionIANA from an options perspective
- Allow for parsed sub-options in OptIAForPrefixDelegation
- Add initial test
=> Add support for DHCPv6-PD sub-options

dhcpv6/server_test.go
"lo" isn't configured everywhere. In FreeBSD for example, TestServerActivateAndServe() fails as the loopback address is "lo0", not "lo".
Also, I don't believe the Zone is required for net.UDPAddr as ::1 is being used, not an fe80:: address. On FreeBSD, since the "lo" Zone doesn't exist, it can't be mapped to an interface index and seems to be silently dropped (I can put "asdf" and it does the same thing). The tests still work fine though.
=> Dynamically determine loopback interface for server test

dhcpv4/bindtodevice_darwin.go, dhcpv4/bindtodevice_linux.go, dhcpv4/bsdp/vendor_class_identifier_darwin.go, dhcpv4/client.go
Fixes #156
Build a simple client like so:
```
package main
import (
"fmt"
"time"
"github.com/insomniacslk/dhcp/dhcpv4"
)
func main() {
client := dhcpv4.Client{ReadTimeout: 5 * time.Second, WriteTimeout: 5 * time.Second}
conversation, err := client.Exchange("en0", nil)
if err != nil {
fmt.Println(err)
}
for _, m := range conversation {
fmt.Println(m.Summary())
}
}
```
and run:
```
$ sudo ./main
Password:
DHCPv4
opcode=BootRequest
hwtype=Ethernet
hwaddrlen=6
hopcount=0
transactionid=0xabfad715
numseconds=0
flags=Broadcast (0x8000)
clientipaddr=0.0.0.0
youripaddr=0.0.0.0
serveripaddr=0.0.0.0
gatewayipaddr=0.0.0.0
clienthwaddr=8c:85:90:20:2e:33
serverhostname=
bootfilename=
options=
DHCP Message Type -> DISCOVER
Parameter Request List -> [Subnet Mask, Router, Domain Name, Domain Name Server] …
```
=> DHCPv4: syscall -> x/sys/unix

dhcpv4/client.go
If the first packet cannot be sent, the function should return an empty slice. Before this patch, it was returning a one-element slice where the element is nil.
=> dhcpv4: fix but in Exchange where a nil packet is returned if send fails

dhcpv6/option_iaprefix.go, dhcpv6/option_iaprefix_test.go
Noticed the length check on ParseOptIAPrefix() is wrong. The other DHCPv6 options seem okay.
=> Avoid panic on malformed OptIAPrefix

dhcpv6/option_prefixdelegation.go, dhcpv6/option_prefixdelegation_test.go
Make the fields of OptIAForPrefixDelegation public. This will make it more consistent with what was done for OptIANA in: https://github.com/insomniacslk/dhcp/commit/bdb0bf25259985b962e230fbac5265a7623afd05
It was not possible to do it in PR #166 because at that point it was going to break router7.
However, this was fixed in https://github.com/rtr7/router7/pull/9.
cc @davebarrau
=> OptIAForPrefixDelegation: make fields public

dhcpv6/option_iaaddress.go, dhcpv6/option_iaprefix.go, dhcpv6/option_iaprefix_test.go, dhcpv6/option_prefixdelegation_test.go
* Parse sub-options of OptIAPrefix to make it consistent with OptIANA, OptIAForPrefixDelegation and OptIAAddress.
* Make fields public also for consistency with other options.
=> OptIAPrefix: sub-options

dhcpv4/client.go
The current DHCPv4 client does not have the ability to specify remote/local addresses/ports. This small patch adds that.
`BroadcastSendReceive()` and `MakeRawBroadcastPacket()` are not used anymore, I did not remove them (since they're public) for backward compatibility.
=> Custom client/server addresses/ports for DHCPv4 client

netboot/netboot.go, netboot/netconf.go
Adds support for `RequestNetbootv4`. The main problem with this implementation is explained in issue #184. If a default route is not added before calling `RequestNetbootv4`, the transaction fails.
=> Add netboot/netconf support for DHCPv4

dhcpv4/ztp/ztp.go, dhcpv4/ztp/ztp_test.go
How about moving the parsing to extract vendor, model and serial from https://github.com/facebookincubator/dhcplb/blob/master/lib/handler.go#L418 to the library.
=> [ztpv4] add Opt60 (vc) parsing

dhcpv4/server.go, dhcpv6/server.go
Not sure why net.Error was being skipped entirely. However that's wrong, only timeouts should be skipped in that code.
=> server: do not skip network errors in ActivateAndServe

dhcpv4/server.go, dhcpv6/server.go
There is no reason to block the network listener on packet handling
=> Make server handlers async

netboot/netconf.go
It is valid to return an empty domain search list
=> netboot: domain search list not mandatory

dhcpv4/client.go, netboot/netconf.go, rfc1035label/label.go
Fixes #184
Tested using u-root and qemu. Also tested on a linux container in a chromebook, see tshark's output at the end.
Build u-root with the dhclient command from https://github.com/insomniacslk/exdhcp (the name clashes with u-root's dhclient, so only building the minimum commands to test):
```
$ go build && ./u-root -build=bb github.com/u-root/u-root/cmds/{init,ip,elvish} github.com/insomniacslk/exdhcp/dhclient
2018/11/18 00:42:59 Disabling CGO for u-root...
2018/11/18 00:42:59 Build environment: GOARCH=amd64 GOOS=linux GOROOT=/home/insomniac/.gvm/gos/go1.10 GOPATH=/home/insomniac/.gvm/pkgsets/go1.10/global CGO_ENABLED=0
2018/11/18 00:42:59 Filename is /tmp/initramfs.linux_amd64.cpio
2018/11/18 00:43:08 Successfully wrote initramfs.
```
Then run it using qemu with `-initramfs` …
=> dhcpv4: run on unconfigured interfaces

rfc1035label/label.go, rfc1035label/label_test.go
The `rfc1035label` module did not support compressed labels, now it does.
Fixes #203
=> rfc1035label: support compression pointers

README.md, dhcpv6/server.go
Added code to the README to run a dummy DHCPv6 server.
See #188
=> Added example for DHCPv6 server

dhcpv4/option_domain_search.go, dhcpv4/option_domain_search_test.go, dhcpv6/option_domainsearchlist.go, dhcpv6/option_domainsearchlist_test.go, netboot/netconf.go, rfc1035label/label.go, rfc1035label/label_test.go
rfc1035label now is implemented on top of a `Labels` struct that contains the original data in case no changes are made. This is required to parse responses from DHCP servers that use label compression.
=> rfc1035label: using a structure to hold original data

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
Added missing error check, which might return more descriptive error to the user when generation error occurs (alternatively we can change the `Read` line to avoid ineffectual assignment)
```go
n, _ := rand.Read(tidBytes)
```
Additionally fixed the tests to work on both LE and BE (previously a BE was assumed).
=> Add missing error check in GenerateTransactionID

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
Allow for mocking a `"crypto/rand"` function in dhcpv6 and improve unit tests.
`randomReadMock` is a standalone function without `mock.Mock` from the testify suite due to multiple errors of `testify/mock` library not properly supporting type aliases (`byte = uint8`) https://github.com/stretchr/testify/issues/692, and the same occurs when using `mock.Anything` (for `[]byte`).
=> Test TransactionID generation

dhcpv4/option_tftp_server_name.go, dhcpv4/server.go, dhcpv4/types.go, dhcpv6/iputils_test.go, dhcpv6/option_vendor_opts.go, dhcpv6/server.go
Removed unreachable code as per `go vet`
=> Removed unreachable code, fixed misspelling

dhcpv6/iputils_test.go
The `err` variable was not checked
=> Added missing check in tests

dhcpv6/dhcpv6_test.go
As the title says. I used `ineffassign` to catch it
=> Removed ineffective assignment

README.md, dhcpv4/bsdp/client.go, dhcpv4/client.go, dhcpv4/server_test.go, dhcpv6/client.go, dhcpv6/server_test.go, netboot/netboot.go
All calls to Exchange(), Solicit() and Request() that I have seen are passing a nil packet.
I think it would be a good idea to simplify this by not passing the packet we want to send and always creating a new one.
The modifiers can completely modify the created packet if needed.
=> simplify client interface

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go, dhcpv4/modifiers_test.go, dhcpv4/option_domain_search.go, dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go, netboot/netconf.go, netboot/netconf_test.go
Same as https://github.com/insomniacslk/dhcp/pull/218 , but for DHCPv4.
I have also simplified the corresponding v6 modifiers, they were unnecessarily complex in #218.
=> Added netconf v4 tests and required modifiers

dhcpv6/ztpv6/README.md, dhcpv6/ztpv6/parse_remote_id.go, dhcpv6/ztpv6/parse_remote_id_test.go, dhcpv6/ztpv6/parse_vendor_options.go, dhcpv6/ztpv6/parse_vendor_options_test.go
This mimics the DHCPv4 vendor option parsing done currently in the DHCPLB algo code.  This should align with the planned directory structure of moving the parsing out of the dhcplb algo and into dhcpv[4|6] directories.
=> Parsing Vendor Opts lib for ztpv6

dhcpv4/ztpv4/ztp.go, dhcpv4/ztpv4/ztp_test.go
* Rename the directory from `ztp` to `ztpv4` to match the package name
* Return an error when calling `ParseVendorData` and no vendor data is found
=> [ztpv4] make it consistent with ztpv6

dhcpv4/async/client.go, dhcpv4/async/client_test.go, dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/bsdp/client.go, dhcpv4/client.go, dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go, dhcpv4/modifiers_test.go, dhcpv4/options.go, dhcpv4/options_test.go, dhcpv4/server_test.go, dhcpv4/types.go, netboot/netboot.go, netboot/netconf.go, netboot/netconf_test.go
Starting with the easy stuff from the other PR. Just cleans up the DHCPv4 type itself, and the marshaling/unmarshaling of data for just the message. Options to come.
=> v4 packet API cleanup

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/bsdp/option_vendor_specific_information.go, dhcpv4/bsdp/option_vendor_specific_information_test.go, dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go, dhcpv4/modifiers_test.go, dhcpv4/option_generic_test.go, dhcpv4/option_message_type_test.go, dhcpv4/option_parameter_request_list.go, dhcpv4/option_parameter_request_list_test.go, dhcpv4/options.go, dhcpv4/server_test.go, dhcpv4/types.go, dhcpv4/ztpv4/ztp_test.go
Removes AddOption and GetOption.
RFC 2131 specifies that options may only appear once (Section 4.1). If
an option does appear more than once, its byte values must be
concatenated.
RFC 3396 further specifies that to send options longer than 255 bytes,
one option may be split into multiple option codes, which must be
concatenated back together by the receiver.
Both of these are concerned with the byte representation of options.
Fact is, based on both RFCs one can say that an option may only appear
once, but may be composed of multiple values. (Like the multiple IP options.)
Because an option may appear only once logically in any case, we remove
the AddOption and GetOption functions and leave only UpdateOption and
GetOneOption.
Also remove all additions & checks of the End option - the …
=> Conform to RFC 3396 & RFC 2131 wrt Options

dhcpv4/dhcpv4.go
In #227, I wrote a test for the Summary stringer:
```
-  transaction ID: 0x01010101
+  transaction ID: 0x30783031303130313031
```
fixing this separately
=> dhcpv4: fix TransactionID in Summary

dhcpv4/async/client.go
It was removed in fe6f307df5d78a54ddd4a56a275043317148fe5a.
It is needed in https://github.com/pinterest/bender/blob/master/dhcpv4/dhcpv4.go#L59.
=> [async] re-add modifiers to Send method

dhcpv4/bsdp/bsdp.go, dhcpv4/bsdp/bsdp_test.go, dhcpv4/bsdp/client.go, dhcpv4/client4/client.go, dhcpv4/defaults.go
This is going to be shared by the server and client code so it should be moved to the main directory. This also makes it consistent with what was done for dhcpv6.
=> [dhcpv4] move default to main directory

.travis/tests.sh, netboot/netconf.go
We hit a bug when Netconf library was failing to bring interface up
despite the fact that it was actually up. It turned out that it's oper
state was not set to UP, what is expected by the library.
According to kernel documentation it is ok proceed if interface state
is Up or Unknown:
```
Interface is in RFC2863 operational state UP or UNKNOWN. This is for
backward compatibility, routing daemons, dhcp clients can use this
flag to determine whether they should use the interface.
```
Also, resaon why operational state may remain Unknown:
```
IF_OPER_UNKNOWN (0):
Interface is in unknown state, neither driver nor userspace has set
operational state. Interface must be considered for user data as
setting operational state has not been implemented in every driver.
```
I modified our code to try …
=> Allow Unknown OperState of the link interface

dhcpv4/dhcpv4.go, dhcpv4/nclient4/client.go, dhcpv4/nclient4/client_test.go, dhcpv4/nclient4/conn_linux.go, dhcpv4/nclient4/ipv4.go, dhcpv4/server4/server.go, dhcpv4/server4/server_test.go
- Able to broadcast UDP before interface is configured.
- RFC2131-compliant retransmission logic.
- Tests.
- Race-condition-averse.
Previous clients (both mine and the ones here) are prone to race
condition errors.
Having one and only one place that calls receive on the socket
"continuously" without having to coordinate hand-offs makes the logic
way easier to follow. We can rely on goroutine scheduling to take care
of some of the blocking semantics.
!! Warning
This PR contains some Apache 2 code taken from gVisor, and the respective file has the header for it.
!! Warning 2
This PR requires Go 1.12.
=> client4: add new DHCPv4 client.

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go
Certain older DHCP servers and relay agents follow the RFC 951 BOOTP
standard in which BOOTP/DHCP messages have a 300 byte minimum length.
cc @ganshun
I'd appreciate the fast path on this review :)
=> dhcpv4: pad v4 messages to a 300 byte minimum

dhcpv4/server4/server_test.go
This is dumb, but when I import this stuff to Google, I can only use ports 32k-64k. I'd like to avoid maintaining an internal patchset on top of dhcp... would y'all be fine taking this?
=> server4 test: pick ports > 32k

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go
As in FromBytes function we are expecting that the version 4 IPs should have length of net.IPv4len which is 4 bytes long. This change will make sure that all the version 4 IPs are written into 4 bytes long format.
Written a unit test for same.
```
go test -run Test_withIP -v
=== RUN   Test_withIP
--- PASS: Test_withIP (0.00s)
PASS
ok      github.com/akshaynawale/dhcp/dhcpv4     0.004s
```
All unit tests result: 
```
=== RUN   TestGetExternalIPv4Addrs
--- PASS: TestGetExternalIPv4Addrs (0.00s)
=== RUN   TestFromBytes
--- PASS: TestFromBytes (0.00s)
=== RUN   TestFromBytesZeroLength
--- PASS: TestFromBytesZeroLength (0.00s)
=== RUN   TestFromBytesShortLength
--- PASS: TestFromBytesShortLength (0.00s)
=== RUN   TestFromBytesInvalidOptions
--- PASS: TestFromBytesInvalidOptions (0.00s)
=== RUN …
```
=> Modifying the writeIP function to always write IPv4 in 4 byte long format

dhcpv4/options.go
After investigation on DHCP relaying with BDCOM P3608 GPON OLT switches, i found that 'End' option is not always padded with 0x00, but for some packets is padded by the same 0xFF (End) option.
DHCPv4 fails to parse such type of packets and throws an "Invalid options" error. But Wireshark says that all is just fine with 0xFF padding.
This commit allows to use 0xFF/0x00 End option padding instead of strict 0x00. This allows BDCOM switches relaying mechanism to work with package.
=> Allow 0xFF padding in 'End' option

dhcpv4/dhcpv4.go, dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
Fixes #246
On QEmu:
* without VirtIO RNG it hangs, `sudo qemu-system-x86_64 -M q35 -kernel arch/x86/boot/bzImage -enable-kvm -nographic`
* with VirtIO RNG it cancels the request, `sudo qemu-system-x86_64 -M q35 -kernel arch/x86/boot/bzImage -enable-kvm -nographic -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0`
=> Use cancellable crypto RNG from u-root

dhcpv6/nclient6/client.go, dhcpv6/nclient6/client_test.go, dhcpv6/server6/server_test.go
- RapidCommit solicits wait for Reply messages, not Advertise.
- Default recipient should be all relay agents and servers, not just
servers.
- Make New() and NewWithConn() interface same as in nclient4.
=> nclient6: small fixes

dhcpv4/server4/server.go, dhcpv6/server6/server.go
Server6 and Server4 had Serve methods that return without reporting an
error, changed in this PR.
Serve now also closes the connection when done.
~~The Server6.Close and Server4.Close methods now also check for nil conn.~~
~~Doing this safely requires an RWLock around `conn`, and doesn't guarantee that the handler will properly lock around using `conn`. I am open to suggestions.~~ EDIT: will reconsider for another PR
=> [server] Serve returns an error, and closes when done

dhcpv6/async/client_test.go, dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go, netboot/netconf_test.go
IAID must be set by the client. This patch generates the IAID from the
MAC address of the interface. To do so, a new WithIAID modifier is
added, the interface of NewSolicitWithCID now requires a hwaddr
parameter, and NewAdvertiseFromSolicit copies the IA_NA option from the
solicit if present.
=> [dhcpv6] Solicit messages derive default IAID from MAC address

dhcpv6/async/client.go, dhcpv6/client6/client.go, dhcpv6/defaults.go, dhcpv6/nclient6/client_test.go, dhcpv6/server6/server.go, dhcpv6/server6/server_test.go, examples/server6/main.go
The previous logic was wrong - there's no "listening" on multicast
address, the server should listen on the given address, and join the
multicast group. This PR fixes it.
Also moved the multicast addresses to a common package.
Tested with unit/integ tests, and with coredhcp.
=> [server6] Server should join multicast address

netboot/netboot.go
The current implementation has a bug, so that it always returns `nil`,
even when an error happened. This PR fixes it.
=> [netboot] Return error when there is one

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go
NewReplyFromMessage creates a reply from a message. With this patch it
can handle Solicit messages with rapid-commit.
RFC3315 states that:
```
If the client has included a Rapid Commit option in its Solicit
message, the client terminates the waiting process as soon as a Reply
message with a Rapid Commit option is received.
```
=> [dhcpv6] Handle SOLICIT with rapid commit in NewReplyFromMessage

dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go
Relays might drop packets coming from clients if they have the Gateway IP set. This modifier is supposed to be used by relays: `WithReply` is used only by clients.
=> [dhcpv4] Do not set Gateway IP address on packets sent by clients

dhcpv6/client6/client.go
The dhcpv6 client was not updating the Remote ID option to the outer encapsulated packet, for SimulateRelay Flag. This was causing problems in testing dhcp requests with Remote ID. As Remote ID is set by the Relay Agent so it should be present at the outer encapsulated packet. This change will copy the inner message's Remote ID option if present, to the outer encapsulated message.
Tested by running unit tests. 
```
go test 
2019/05/07 15:58:22 DNS OptDNSRecursiveNameServer{nameservers=[fe80::1 fe80::2]}
PASS
ok      _/home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv6        0.009s
```
=> Adding RemoteID option while creating a Relayed Encapsulated Packet 

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go
After PR #287 we no longer copy the gw ip. However that is needed on server replies.
=> NewReplyFromRequest: copy gw ip

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/option_string_test.go
- dnsmasq has been seen to null-terminate the bootfile option.
- for the gateway/dns information to be present in final packet,
the Router option should be queried again in request as
in discover (which matches behavior of udhcpc/dhclient).
Tested: pxeboot with u-root on dnsmask/ipv4 client.
=> Improve compatibility with some ipv4 networks.

dhcpv4/ztpv4/parse_circuitid.go, dhcpv4/ztpv4/parse_circuitid_test.go
Some Vendors like Arista sends SHIFT IN (0x000f) prefix to the circuit id. This used to fail the circuit id parsing logic. This check will remove the 0x000f bytes prefix from the circuit id field if present. 
Added unit test for the same.
Signed-off-by: Akshay Navale <navale@fb.com>
```
go test
PASS
ok      _/home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv4/ztpv4  0.004s
```
=> Remove SHIFT IN character bytes from Circuit ID

dhcpv4/ztpv4/parse_circuitid.go, dhcpv4/ztpv4/parse_circuitid_test.go
This change will allow us to parse Juniper EX series interface pattern. 
Adding the regex and unit test for the same.
Tested with unit tests.
```
go test
PASS
ok      _/home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv4/ztpv4  0.004s
```
Signed-off-by: Akshay Navale <navale@fb.com>
=> Adding Juniper EX pattern for circuit parsing

dhcpv4/ztpv4/parse_circuitid.go, dhcpv4/ztpv4/parse_circuitid_test.go
Sometimes Arista devices send CircuitID type (1byte) and Circuit ID Length (1 byte) in Relay Agent Option 82's Suboption 1 field's value. Therefore, changing Arista regex to not match with starts with "^" character to consider this.  (Earlier I thought the prepended bytes are just random characters, Arista devices are sending, and added a check to remove 0x00 0x0F. Removing that in this pull request too.)
tested with unit tests (modified unit tests accordingly.)
```
go test
PASS                                                                          
ok      _/home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv4/ztpv4  0.004s
```
Signed-off-by: Akshay Navale <navale@fb.com>
=> Changing Arista CircuitID regex for prepended type and length field

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go
Usually this is used for clients that don't know how to receive any
other packets. We can deal with both a unicast or broadcast response
packet, so let's let the server decide on its own.
=> v4 discover: don't ask for broadcast

dhcpv4/nclient4/client_test.go, dhcpv4/server4/server.go
Clients without an IP set their source address to 0.0.0.0, so the peer
returned by ReadFrom may not actually be the address to send to.
Clients without an IP should have their response broadcast.
=> server4: set peer to broadcast if client IP is zero

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go
In DHCPv4, when the ParameterRequestList option is not present in a request, I believe it should be assumed that the client wants to receive all the options that the server is able to send.
This changes the IsOptionRequested method of dhcpv4.DHCPv4 to return true for any request in that situation.
The reasoning is based on this wording in [RFC2131§3.5](https://tools.ietf.org/html/rfc2131#section-3.5):
> Not all clients require initialization of all parameters listed in
> Appendix A. Two techniques are used to reduce the number of
> parameters transmitted from the server to the client. [...] Second, in
> its initial DHCPDISCOVER or DHCPREQUEST message, a client may provide
> the server with a list of specific parameters the client is interested
> in.
Initially raised in …
=> dhcpv4: Mark all options as requested absent ParameterRequestList

dhcpv6/server6/server.go
This way, you can use `&net.UDPAddr{Port: 547}` without having to actually put an IP down
=> server6: allow nil IP in addition to unspecified

dhcpv6/dhcpv6.go, dhcpv6/dhcpv6_test.go, dhcpv6/fuzz.go, iana/hwtypes.go
Since this library parses sometimes untrusted data, I thought it would be relevant to add fuzzing support to make sure we act reasonably whatever the data.
This adds a fairly simple fuzzing entrypoint for dhcpv6 (I have the same in the pipe for dhcpv4, but it needs a bit more work), which parses a message, then writes it back out, and compares them.
This is fairly limited obviously: 
* Maybe not all messages don't need to be byte-for-byte identical after being deserialized-serialized, causing some false-positives. This hasn't caused issues yet though
* It would only catch bugs in messages that come from deserializing, not from messages being crafted using the library
See the page for go-fuzz for usage instructions: https://github.com/dvyukov/go-fuzz; but basically:
```
go get …
```
=> dhcpv6: Basic fuzzing support and fixes for discovered bugs

dhcpv4/server4/conn.go, dhcpv4/server4/server.go, dhcpv4/server4/server_test.go
It was mentioned in #326 that NewIPv4UDPConn doesn't support listening on a specific address, only on the wildcard address. This extends it to allow listening on an address, and at the same time homogenizes the function signature with the NewIPv6UDPConn server6 equivalent. It modifies NewServer() to pass the full address given to it instead of just the port as well
Note that listening on a non-wildcard interface is seldom useful as the socket won't receive broadcasts, so it is useless in a direct-attached server. It can be useful in a server only used behind relays
This breaks API compatibility for NewIPv4UDPConn, which as far as I know/on github nobody uses (yet)
=> server4: Allow listening on a non-wildcard IP address on v4

dhcpv4/option_relay_agent_information.go
These additional sub options are in the Standards Track.
=> Added additional DHCP4 Relay Agent Information sub options (as per various RFCs).

dhcpv6/option_4rd.go, dhcpv6/option_4rd_test.go, dhcpv6/options.go, dhcpv6/types.go
This PR includes option parsing for 4RD options defined in RFC7600
The first commit is a preparation commit which adds the necessary Option* constants; I took the opportunity to update the table up to the current version of the [IANA table](https://www.iana.org/assignments/dhcpv6-parameters/dhcpv6-parameters.xhtml#dhcpv6-parameters-2)
The second commit includes struct definitions, parsing and serializing for the 3 option types defined in [RFC7600§4.9](https://tools.ietf.org/html/rfc7600#section-4.9)
Additional comments on specific lines of the code inline
=> dhcpv6: 4RD option support

dhcpv6/ztpv6/parse_vendor_options.go, dhcpv6/ztpv6/parse_vendor_options_test.go
Some network vendors (like ZPE) use Opt 16 (VendorClass) instead of Opt17 (VendorOptions) to send vendor data. This change will allow us to consider data in option 16 for such devices for ParseVendorData function. Added new unit tests for this scenario as well. 
Test Results:
```
go test -v                      
=== RUN   TestCircuitID
=== RUN   TestCircuitID/Bogus_string
=== RUN   TestCircuitID/Arista_Port_Vlan_Pattern
=== RUN   TestCircuitID/Arista_Slot_Module_Port_Pattern
--- PASS: TestCircuitID (0.00s)
--- PASS: TestCircuitID/Bogus_string (0.00s)
--- PASS: TestCircuitID/Arista_Port_Vlan_Pattern (0.00s)
--- PASS: TestCircuitID/Arista_Slot_Module_Port_Pattern (0.00s)
=== RUN   TestFormatCircuitID
=== RUN   TestFormatCircuitID/empty
=== RUN   TestFormatCircuitID/Arista_format_Port/Vlan …
```
=> [dhcpv6] Adding opt 16 when parsing vendor data

dhcpv4/dhcpv4.go, dhcpv4/modifiers.go, dhcpv4/modifiers_test.go
Here is an initial PR for adding support to copy relay options if they exist in a request to dhcpv4.NewReplyFromRequest.  RFC3046 section 2.2 specifies "DHCP servers claiming to support the Relay Agent Information option SHALL echo the entire contents of the Relay Agent Information option
in all replies." so I think it is safe to add to the NewReplyFromRequest function.
Perhaps the new function should be name CopyRelayOptions instead of WithRelayOptions?
=> Add support for copying relay options

.travis.yml, .travis/tests.sh, dhcpv4/client4/client.go, dhcpv4/nclient4/client.go, dhcpv4/nclient4/conn_linux.go
Related: https://github.com/insomniacslk/dhcp/issues/334
The PR is supposed to reduce costs of migrating from client4 to nclient4.
Changes in [nclient4](https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/nclient4/client.go):
* Published `Logger`. So now somebody can use option `WithLogger` and define own logger or/and to use a builtin logger. And added comment `print _all_ DHCP messages` to guarantee (to an external user) and to remind (to an internal developer) that PrintMessage always prints all messages. So in task https://github.com/insomniacslk/dhcp/issues/334 it's possible to use this loggers instead of changing `Request`, now.
* Fixed the problem with unicast frames. Previously `nclient4` was always sending broadcast frames. But our utility (related to …
=> Simplified porting from client4 to nclient4

dhcpv4/nclient4/client.go
This option allows to receive answers DHCP with arbitrary client addresses.
=> Added option nclient4.WithHWAddr

dhcpv6/client6/client.go, dhcpv6/option_bootfileparam.go, dhcpv6/option_bootfileparam_test.go, dhcpv6/options.go, netboot/netboot.go
See RFC5970 section 3.2.
* Added support of option OptBootFileParam
* Added BootfileParam to netboot results
=> Add option BootfileParam

netboot/rtnetlink_linux.go
On machines with many NICs, it can cause the golang runtime to run out of threads.
=> Fix "conn" leaking

dhcpv6/nclient6/client.go
This allows for multi-NIC DHCPv6 in parallel.
Otherwise:
2020/02/20 05:01:34 Could not configure eth1 for IPv6: listen udp6 %eth1:546: bind: address already in use
2020/02/20 05:01:34 Could not configure eth4 for IPv6: listen udp6 %eth4:546: bind: address already in use
2020/02/20 05:01:34 Attempting to get DHCPv6 lease on eth2
2020/02/20 05:01:34 Could not configure eth0 for IPv6: listen udp6 %eth0:546: bind: address already in use
2020/02/20 05:01:34 Could not configure eth3 for IPv6: listen udp6 %eth3:546: bind: address already in use
=> nclient6: listen on link-local addr

dhcpv6/option_iaprefix.go, dhcpv6/option_iaprefix_test.go
Don't require initialization of the prefix in an OptIAPrefix struct. Set the set the
IPv6 prefix field to zero in the message if the prefix in uninitialized or contains an invalid IPv6 address.
=> dhcpv6: allow using OptIAPrefix without initializing

dhcpv6/dhcpv6message.go
Added IAAddress, OneIAAddress, UserClasses, VendorOpts, and changed
Options to MessageOptions in IA_NA and IA_Address options.
=> [dhcpv6] More getters for MessageOptions

dhcpv6/modifiers.go, dhcpv6/option_iaaddress.go, dhcpv6/option_iaaddress_test.go, dhcpv6/option_nontemporaryaddress.go, dhcpv6/option_nontemporaryaddress_test.go, netboot/netconf.go
IA_NA and IA_TA options can contain two fields:
- IAAddress
- Status Code
IAAddress may contain one field:
- Status Code
(See RFC 8415 Appendix C for this info.)
This adds two types, IdentityOptions and AddressOptions with Getters for each of the allowed option types.
=> v6: introduce IdentityOptions and getters

dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go, dhcpv6/modifiers_test.go, dhcpv6/option_dhcpv4_msg.go, dhcpv6/option_dhcpv4_msg_test.go, dhcpv6/option_dhcpv4_o_dhcpv6_server.go, dhcpv6/option_dhcpv4_o_dhcpv6_server_test.go, dhcpv6/options.go, dhcpv6/types.go
Add message types, options, and modifier for handling DHCPv4-over-DHCPv6.
Refer to RFC 7341
=> dhcpv6: add DHCPv4-over-DHCPv6 support

dhcpv6/dhcpv6relay.go, dhcpv6/dhcpv6relay_test.go, dhcpv6/option_iaaddress.go, dhcpv6/option_iaaddress_test.go, dhcpv6/option_iaprefix.go
=> dhcpv6: always write 16-byte IPs

dhcpv6/dhcpv6message.go
RFC 8415 Section 21.17 states it may appear more than once:
Multiple instances of the Vendor-specific Information option may
appear in a DHCP message.  Each instance of the option is interpreted
according to the option codes defined by the vendor identified by the
Enterprise Number in that option.  Servers and clients MUST NOT send
more than one instance of the Vendor-specific Information option with
the same Enterprise Number.
=> dhcp6: fix VendorOpts getter

dhcpv6/dhcpv6.go, dhcpv6/dhcpv6relay.go, dhcpv6/dhcpv6relay_test.go, dhcpv6/option_interfaceid.go, dhcpv6/option_interfaceid_test.go, dhcpv6/option_relaymsg.go, dhcpv6/option_relaymsg_test.go, dhcpv6/option_remoteid.go, dhcpv6/option_remoteid_test.go, dhcpv6/options.go, dhcpv6/ztpv6/parse_remote_id.go, dhcpv6/ztpv6/parse_remote_id_test.go
According to RFC 8415 Appendix C, RelayForw and RelayRepl messages may have the following options:
- RelayMessage
- InterfaceID
- Vendor Info (unimplemented)
RFC 4649 also adds a RemoteID to relay messages.
This adds a `RelayOptions` type with Getters for RelayMessage, InterfaceID, and RemoteID.
=> v6: introduce RelayOptions and getters

dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go, dhcpv6/modifiers_test.go
Add the IA_PD option to the request from the advertise if present.
Add WithIAPD() as modifier and test.
=> dhcpv6: add IA_PD to request from advertise

dhcpv6/ztpv6/parse_remote_id.go, dhcpv6/ztpv6/parse_remote_id_test.go
Arista Devices for DHCPv6 send circuit id information in option 18 when the relay interface is L3 interface (not vlan interface) so adding this logic. If we dont find circuit id from option 37 ( remote id ) then look for option 18 (interface id). 
unit rest result
```
➜ /home/navale/go/src/github.com/akshaynawale/dhcp/dhcpv6/ztpv6 git:(master) go test -v
=== RUN   TestCircuitID                                                                                                                                                                                                                       
=== RUN   TestCircuitID/Bogus_string …
```
=> adding fallback logic to remote id parsing

dhcpv6/dhcpv6message.go
Per the RFC each new Exchange should have a new TransactionID. Clients should not reuse the same transaction ID for a new REQUEST from a SOLICIT
=> Generate new TransactionID for Request

.travis.yml, .travis/linters.sh
* bump Go versions
* use Go modules when downloading golangci-lint
* use $GOPATH when running golangci-lint bin
=> fix golangci-lint

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/fuzz.go, dhcpv4/option_routes.go, dhcpv4/option_routes_test.go, dhcpv4/options.go, dhcpv4/options_test.go
This PR adds a go-fuzz endpoint (similar to #325) and fixes a few panics that it discovered, as well as an RFC violation. 
See individual commits for further details, but for a quick summary:
* Patch 1 and 2 are preparation, they introduce the fuzzing entrypoint and refactor a test for ease-of-use
* Patch 3 fixes a panic with strings over their size limit in writing out packets
* Patch 4 removes a special case in ToBytes() that prevents from crafting some arbitrary packets with hlen=0. This warrants extra attention because it could break applications that do not use any of the `New()` functions to create a packet but instead craft them manually, **and** leave the `ClientHWAddr` field empty to rely on `ToBytes()` to initialize it to the `00:00:00:00:00:00` Ethernet address. Seems unlikely …
=> dhcpv4: Fix some panics found by fuzzing

netboot/netconf.go
Since we do not share this code at the moment, here's a dup of https://github.com/u-root/u-root/pull/1765
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684009
"Note that the dhcpv6 protocol doesn't have an option for a netmask. So
it is always /128 and routing is left to icmpv6 router advertisements."
RFC 5942 is a good read here as well:
An address could be acquired through the DHCPv6 identity association
for non- temporary addresses (IA_NA) option from [RFC3315] (which
does not include a prefix length), or through manual configuration
(if no prefix length is specified).  The host incorrectly assumes an
invented prefix is on-link.  This invented prefix typically is a /64
that was written by the developer of the operating system network
module API to any IPv6 application as a …
=> netconf: apply v6 addresses as /128

dhcpv6/dhcpv6message.go, dhcpv6/modifiers.go, dhcpv6/option_temporaryaddress.go, dhcpv6/option_temporaryaddress_test.go, dhcpv6/options.go
This creates support for IA_TA options, based on and reusing the blocks from IA_NA, to which it is extremely similar (It's the same, but with T1 and T2 removed)
=> dhcpv6: Handle IA_TA options

dhcpv6/iputils.go
Use option 79 if available when looking for the MAC address.
=> ExtractMAC: use option 79

iana/archtype.go
Adds the additional architecture types as defined by IANA
http://www.iana.org/assignments/dhcpv6-parameters/dhcpv6-parameters.xhtml#processor-architecture.
Note, RFC4578 errata, https://www.rfc-editor.org/errata_search.php?rfc=4578
"The values for EFI BC and EFI x86-64 should be swapped. UEFI implementations use value 7 to report EFI x86-64, not value 9."
IANA's list also agrees with this swap. Thus I've swapped these values here to match.
I took some liberty with the new architecture's mnemonic names compared to the descriptions from IANA. This was an attempt to standardize wording, capitalization, and match the existing style.
=> Add Additional IANA Architecture Types

dhcpv4/nclient4/client.go
The default port for a UDP connection of client should be 68, not 67.
=> nclient4: WithUnicast default port should be 68

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv6/option_dhcpv4_msg_test.go
RFC 2131 gives two examples of padding in section 4.1. For both the
examples, the 'end' option preceeds the padding with the 'pad' option.
These examples relate to overloading pre-defined fields for options,
not padding the packet for a minimal size.
Older versions of the U-Boot firmware support DHCP, but do not expect
the 'pad' option. The firmware logs the following warning for each
occurence:
*** Unhandled DHCP Option in OFFER/ACK: 0
This warning disappears when the 'end' option preceeds the 'pad'
option.
Signed-off-by: Marcel Moolenaar <mmoolena@amazon.com>
=> Pad packets after the 'end' option to be more conformant

dhcpv4/dhcpv4.go, dhcpv4/option_string_test.go
We, the _AdGuard_ team, have received an [issue](https://github.com/AdguardTeam/AdGuardHome/issues/2582) some time ago.  After researching a little we've found that some devices may include trailing zero-byte in [DHCP option 12](https://tools.ietf.org/html/rfc2132#section-3.14) length calculation.  We've also found that similar issues with some other options were already solved in fcbde74dab23754aa33fbcd409327c0a1409f2a7.
For now, we've come up with a [little workaround](https://github.com/AdguardTeam/AdGuardHome/commit/5aa0ca9319919f35eb2e1dc4c9e6d8f0385c394e) in _AdGuard Home_, but it's a temporary solution.  Please review our little fix, we hope to get rid of our crutch as soon as possible :)
=> Improve compatibility with some devices

dhcpv4/ztpv4/parse_circuitid_test.go
Incorrect test case was modified in https://github.com/insomniacslk/dhcp/pull/418.
Reverting modified test case for "Juniper QFX pattern" and moving test case closer to "juniperQFX pattern".
=> rearrange parse_circuitid test cases

dhcpv4/server4/conn_unix.go, dhcpv4/server4/conn_windows.go, interfaces/bindtodevice_windows.go
I am working on an userland network stack based on gvisor (https://github.com/containers/gvisor-tap-vsock).
I use this library as the dhcp server. It works really great but doesn't compile on Windows.
This PR allows to start the server on Windows with a net.PacketConn directly `server4.WithConn()`. 
It also requires this PR in u-root: https://github.com/u-root/u-root/pull/2019
=> Make server4 package compile on Windows

dhcpv6/server6/conn_unix.go, dhcpv6/server6/conn_windows.go
This PR mirrors the change in https://github.com/insomniacslk/dhcp/pull/428 in order to make `server6` compile on Windows by adding a dummy `NewIPv6UDPConn` function.
=> Make server6 package compile on Windows

dhcpv4/nclient4/conn_linux.go
This should fix the panic we've seen with the malformed packets on the
wire. Remaining buffer size should be checked before trying to access
the data, otherwise Go might panic on out of bounds slice operation.
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
=> fix: check IP/UDP header size before trying to access it

dhcpv6/ztpv6/parse_vendor_options.go, dhcpv6/ztpv6/parse_vendor_options_test.go
Adding ZTPv6 Cisco support based on Option 17 Suboption 1 (Vendor Specific Information Option).
=> Add Cisco ZTPv6 Support

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/modifiers.go, dhcpv4/modifiers_test.go, dhcpv4/nclient4/client.go, dhcpv4/nclient4/lease.go, dhcpv4/nclient4/lease_test.go, dhcpv4/options.go, dhcpv4/server4/server_test.go
When using `nclient4.RequestFromOffer` with an existing offer to issue lease renewals, `OptionRequestedIPAddress` and `OptionServerIdentifier` must be cleared to comply with [RFC 2131, section 4.3.2] (RENEW). Updating these with modifiers using `dhcpv4.WithOption` does work, but setting the IP addresses to `nil` causes `Options` keep them which results in an invalid DHCP packet that has entries with without values. This fix implements a new `WithoutOption` modifier that can be used to clear those options.
Additionally, it also enables native issuing of renew requests with a new `nclient4.Client.Renew` method using the aforementioned functionality.
[RFC 2131, section 4.3.2]: https://datatracker.ietf.org/doc/html/rfc2131#section-4.3.2
=> dhcpv4: support RENEW requests and option deletion

rfc1035label/label.go, rfc1035label/label_test.go
This PR only contains a failing test case for #466. I don't know enough about RFC 1035 (especially compressed ones) to be comfortable implementing a solution that does not break anything.
=> Add Support for Labels Containing Partial Domain Names (RFC 4704 Section 4.2)

dhcpv4/nclient4/lease.go, dhcpv4/nclient4/lease_test.go, dhcpv4/server4/server_test.go
Follow-up of https://github.com/insomniacslk/dhcp/pull/469#discussion_r967858102, `Renew()` should return a new lease upon successful renewal instead of modifying the one passed in by reference.
=> dhcpv4: return a new lease from Renew()

dhcpv4/server4/server_test.go
Any parameter passed to `require.NotNil()` after the first two will not be tested but instead appended to the message that is printed if the test fails. This means that `lease.ACK` was never tested to not be nil.
=> dhcpv4: fix require.NotNil() usage in tests

dhcpv4/dhcpv4_test.go
`NewInform()` exposes a consumer-facing interface that accepts modifiers, but this functionality is never tested unlike with for example `NewRequest()` and `NewRenew()`. To ensure that modifiers are correctly respected and any future modifications won't break this support, add a modifier test for `NewInform()`.
=> dhcpv4: add test for NewInform() with modifiers

dhcpv4/dhcpv4.go
This is just a minor readability improvement that makes `NewInform()` consistent with the neighboring functions like `NewRequest()`, `NewReply()`, `NewRelease()` etc. Having the prepended modifiers on the same line helps with separating the modifiers that provided by the function from the modifiers passed in by the consumer of the function.
=> dhcpv4: make NewInform() formatting consistent with neighbors

netboot/netboot.go
The current behavior of `RequestNetbootv4` is potentially dangerous because when it reaches the max number of retries, it returns `conversation, nil` (line 91) back to the caller, even if `client.Exchange()` (line 77) returned an `err`. This leads to a situation where the caller will see `err == nil` but incorrect data returned via the other parameter.
This changes the behavior to match the behavior of `RequestNetbootv6`.  If this change isn't allowed because it's not backwards compatible then we should at least consider returning `nil, nil` instead of `conversation, nil` on the final retry.
I found this while investigating potential nil pointers at https://github.com/u-root/u-root/issues/2517
Signed-off-by: Avi Brender <avibrender@gmail.com>
=> Return error from RequestNetbootv4

dhcpv6/dhcpv6_test.go, dhcpv6/dhcpv6message.go, dhcpv6/dhcpv6relay_test.go, dhcpv6/duid.go, dhcpv6/duid_test.go, dhcpv6/iputils.go, dhcpv6/iputils_test.go, dhcpv6/modifiers.go, dhcpv6/modifiers_test.go, dhcpv6/option_clientid.go, dhcpv6/option_clientid_test.go, dhcpv6/option_serverid.go, dhcpv6/option_serverid_test.go, dhcpv6/prettyprint_test.go, dhcpv6/ztpv6/parse_vendor_options.go, dhcpv6/ztpv6/parse_vendor_options_test.go, examples/packetcrafting6/main.go
Types now only allow valid combination of DUID data.
Before:
```go
// Duid is a DHCP Unique Identifier.
type Duid struct {
Type                 DuidType
HwType               iana.HWType // for DUID-LLT and DUID-LL. Ignored otherwise. RFC 826
Time                 uint32      // for DUID-LLT. Ignored otherwise
LinkLayerAddr        net.HardwareAddr
EnterpriseNumber     uint32 // for DUID-EN. Ignored otherwise
EnterpriseIdentifier []byte // for DUID-EN. Ignored otherwise
Uuid                 []byte // for DUID-UUID. Ignored otherwise
Opaque               []byte // for unknown DUIDs
}
```
After:
```go
// DUID is the interface that all DUIDs adhere to.
type DUID interface {
fmt.Stringer
ToBytes() []byte
FromBytes(p []byte) error
DUIDType() DUIDType
Equal(d DUID) bool
}
// DUIDLLT is a DUID …
```
=> dhcpv6: proper DUID types

go.mod, go.sum
https://github.com/pierrec/lz4/issues/203
dhcp is not even directly using lz4, but because u-root is, having v4.1.17 listed here forces u-root to choose the larger version in MVS. u-root has to choose v4.1.14 until the bug is resolved.
So downgrading here as well.
=> Pin lz4 to v4.1.14 due to bug

dhcpv4/dhcpv4.go, dhcpv4/dhcpv4_test.go, dhcpv4/nclient4/lease.go
Minor fixup for https://github.com/insomniacslk/dhcp/pull/469.
=> dhcpv4: change `NewRenewFromOffer` to `NewRenewFromAck`

dhcpv4/nclient4/conn_unix.go, go.mod, go.sum
https://github.com/mdlayher/raw is deprecated and easily replaced with https://github.com/mdlayher/packet
=> Remove mdlayher/raw dep

dhcpv6/ztpv6/mellanox.go, dhcpv6/ztpv6/mellanox_test.go, dhcpv6/ztpv6/parse_vendor_options.go, iana/entid.go
MLNX-OS sends DHCP information spread in different vendor options sub-options: https://docs.nvidia.com/networking/display/MLNXOSv3103002/Getting+Started#heading-RunningDHCP-ZTP
Enterprise number 33049 is registered to Mellanox: https://www.iana.org/assignments/enterprise-numbers/?q=33049
Adding support to parse the VendorOptions and return the standard VendorData struct.
=> Add MLNX-OS ZTPv6 vendor data parsing

dhcpv4/nclient4/conn_unix.go, interfaces/bindtodevice_bsd.go
This adds DragonFly BSD to the list of BSDs so that lima-vm can be built (https://github.com/lima-vm/lima/issues/892)
=> Porting work for DragonFly BSD

go.mod, go.sum
`github.com/mdlayher/socket v0.5.0` need golang1.21
maybe downgrade to v0.4.1 is better
=> downgrade mdlayher/socket to v0.4.1 for go 1.20

dhcpv4/options.go, dhcpv4/options_test.go
https://datatracker.ietf.org/doc/html/rfc3046#section-2.1 states:
```
A DHCP relay agent adding a Relay Agent Information field SHALL add
it as the last option (but before 'End Option' 255, if present) in
the DHCP options field of any recognized BOOTP or DHCP packet
forwarded from a client to a server.
```
=> Make Option 82 come last

dhcpv6/ztpv6/parse_vendor_options.go, dhcpv6/ztpv6/parse_vendor_options_test.go
Adding support for NVOS ZTPv6 via Option 16 (Vendor Class Option) because it will be needed for bootstrapping.
=> Add ZTPv6 NVOS Support

dhcpv4/options.go, dhcpv4/options_test.go
RFC 2132 says:
`The end option marks the end of valid information in the vendor field.  Subsequent octets should be filled with pad options.`
But it seems that this does not mean that the client should consider packages with non-pad options after the End option invalid, because RFC 2119 explains:
`3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.`
This PR is an alternative to https://github.com/insomniacslk/dhcp/pull/543 and https://github.com/insomniacslk/dhcp/pull/545.
=> Remove zero padding check

dhcpv4/option_relay_agent_information.go, dhcpv4/option_relay_agent_information_test.go, dhcpv4/options_test.go
Printing strings that contain binary messes up my terminal. Using %q instead of %s will result in the binary being escaped.
=> Escape agent options containing binary when stringifying

dhcpv4/dhcpv4.go, dhcpv4/option_ips.go, dhcpv4/option_ips_test.go, dhcpv4/types.go
https://datatracker.ietf.org/doc/html/rfc2132#section-8.5
Add functions to create & get option for NetBIOS Name Servers from IPs
=> dhcpv4: Add opt function for NetBIOS Name Servers

dhcpv4/dhcpv4.go
These new functions are equivalent, but allow callers to pass a context down from main (or equivalent).  This is necessary to comply with certain style guides, for example, https://google.github.io/styleguide/go/decisions#contexts.
We considered replacing dhcpv4.GenerateTransactionID with rand.Read(xid[:]) based on the godoc saying that Read call "never returns an error", but this package is used in embedded situations where it can fail.
=> Add WithContext versions of functions that use contexts.

dhcpv4/client4/client.go, dhcpv4/server4/conn_unix.go, dhcpv6/server6/conn_unix.go, internal/xsocket/xsocket.go, internal/xsocket/xsocket_cloexec.go, internal/xsocket/xsocket_nocloexec.go
Go runtime adds `CLOEXEC` flags automatically, but when using raw syscalls, we have to do it manually.
Without this flag, file descriptors leak to the child processes.
=> fix: add CLOEXEC flag to socket created directly
